<a href="https://colab.research.google.com/github/SakshiKhare7/Learning-Data-Analysis/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [ ]:
a = np.array([1,2,3])
print (a)


[1 2 3]


In [ ]:
b= np.array([[9,0,8,0,7,0],[6,7,8,9,9,4]])
print(b)

[[9 0 8 0 7 0]
 [6 7 8 9 9 4]]


In [ ]:
# Get Dimension
a.ndim


1

In [ ]:
#Get shape
b.shape

(2, 6)

In [ ]:
# Get Type
a.dtype

dtype('int64')

In [ ]:
#Get Size
a.itemsize

8

In [ ]:
#Get total size
a.nbytes

24

Accessing or Changing specific elements, rows,columns etc


In [ ]:
a = np.array([[5,7,5,6,8,2,4],[1,2,3,4,5,6,60]])
print(a)

[[ 5  7  5  6  8  2  4]
 [ 1  2  3  4  5  6 60]]


In [ ]:
#Get a specific element [r,c]
a[1,5]

6

In [ ]:
#Get a spcific row
a[0,:]

array([5, 7, 5, 6, 8, 2, 4])

In [ ]:
#Get a specific column
a[:,2]

array([5, 3])

In [ ]:
#Fancy way[startindex:endindex:stepsize]
a[0,1:-1:2]

array([7, 6, 2])

In [ ]:
a[1,5]= 20
print(a)

[[ 5  7  5  6  8  2  4]
 [ 1  2  3  4  5 20 60]]


In [ ]:
a[1,5] = 20
a[:,2] =[1,2]
print(a)

[[ 5  7  1  6  8  2  4]
 [ 1  2  2  4  5 20 60]]


3-d example

In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Get specific element (work outside in)
b[0,1,1]

4

In [ ]:
#replace
b[:,1,:]



array([[3, 4],
       [7, 8]])

In [ ]:
b[:,1,:]=[[9,9],[8,8]]

Initializing different types of Arrays

In [ ]:
#All 0s matrix
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#All is matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
#Any other number
np.full((2,2),99)


array([[99, 99],
       [99, 99]])

In [ ]:
#Any other number
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [ ]:
#Any other numbeer(full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
#Random decimal numbers
np.random.rand(4,2)

array([[0.26853525, 0.89289403],
       [0.30619256, 0.23494606],
       [0.09584199, 0.8233407 ],
       [0.80338481, 0.99207876]])

In [ ]:
#Random Integer Value
np.random.randint(7, size=(3,3))

array([[2, 1, 3],
       [0, 3, 2],
       [5, 2, 4]])

In [ ]:
#The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#Repeat an array
arr =np.array([1,2,3])
rl= np.repeat(arr,3)
print(rl)

[1 1 1 2 2 2 3 3 3]


In [5]:
arr =np.array([[1,2,3]])
rl= np.repeat(arr,3,axis=0)
print(rl)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [6]:
arr = np.array([[1,2,3]])
rl = np.repeat(arr,3,axis =1)
print(rl)

[[1 1 1 2 2 2 3 3 3]]


In [3]:
output = np.ones((5,5))
print(output)
z= np.zeros((3,3))
z[1,1]=9
print(z)
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
output = np.ones((5,5))
print(output)
z= np.zeros((3,3))
z[1,1]=9
print(z)
output[1:-1,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be careful when copying arrays

In [7]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)

[100   2   3]


In [10]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [11]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [12]:
a+2

array([3, 4, 5, 6])

In [13]:
a-2

array([-1,  0,  1,  2])

In [14]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

Linear Algebra


In [17]:
a = np.ones((2,3))
print(a)
b= np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [18]:
a = np.ones((2,4))
print(a)
b= np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [20]:
#Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

Statistics


In [22]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
np.min(stats)

1

In [24]:
np.max(stats)

6

In [26]:
np.max(stats,axis=1)

array([3, 6])

In [27]:
np.sum(stats)

21

In [28]:
np.sum(stats,axis = 0)

array([5, 7, 9])

Reorganizing Arrays


In [30]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [32]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [34]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [36]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

Miscellaneous



Load data from file


In [38]:
#np.genfromtxt('data.txt',delimiter=',')

Boolean Masking and Advanced indexing


In [45]:
# You can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]


array([2, 3, 9])